# Generated by Django 2.0.6 on 2018-10-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20181013_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='found',
            name='provider_number',
            field=models.CharField(default=1234567890, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lost',
            name='provider_number',
            field=models.CharField(default='1234567890', max_length=10),
            preserve_default=False,
        ),
    ]
