# Generated by Django 2.0.6 on 2018-10-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20181018_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='found',
            name='Photo',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='lost',
            name='Photo',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
