# Generated by Django 2.0.6 on 2018-10-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20181018_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='found',
            name='person_id',
            field=models.CharField(default='123fafvsv11323', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lost',
            name='person_id',
            field=models.CharField(default='13443dsgbgbdb', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lost',
            name='Photo',
            field=models.FileField(default='fgaDvggfaasfwfwef', upload_to='media'),
            preserve_default=False,
        ),
    ]
