# Generated by Django 2.0 on 2018-10-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20181019_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='found',
            name='status',
            field=models.CharField(default='Not Found', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lost',
            name='status',
            field=models.CharField(default='Not found', max_length=20),
            preserve_default=False,
        ),
    ]
