# Generated by Django 2.0 on 2018-10-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20181022_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoundId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LostId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='found',
            name='person_id',
        ),
        migrations.RemoveField(
            model_name='lost',
            name='person_id',
        ),
    ]
