# Generated by Django 2.0 on 2018-10-25 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20181024_1757'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoundId',
        ),
        migrations.DeleteModel(
            name='LostId',
        ),
    ]
