# Generated by Django 2.0 on 2018-10-25 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_foundid_lostid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foundid',
            name='link',
        ),
        migrations.RemoveField(
            model_name='lostid',
            name='link',
        ),
        migrations.DeleteModel(
            name='FoundId',
        ),
        migrations.DeleteModel(
            name='LostId',
        ),
    ]
