# Generated by Django 2.0 on 2018-10-25 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_auto_20181025_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='idfound',
            fields=[
                ('link', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='webapp.Found')),
                ('person_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='idlost',
            fields=[
                ('link', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='webapp.Lost')),
                ('person_id', models.CharField(max_length=200)),
            ],
        ),
    ]
